version: '3.4'

services:
  mongocrud:
    image: mongocrud
    container_name: "mongocrud"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    links: 
      - mongodb

  mongodb:
    image: mongo
    container_name: "mongodb"
    restart: always
    ports: 
      - 27017:27017
